/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/books.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        scale={[0.784, 0.068, 0.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cover.geometry}
        material={nodes.cover.material}
        position={[0.001, -0.132, 0]}
        scale={[0.784, 0.068, 0.609]}
      />
    </group>
  )
}

useGLTF.preload('/books.glb')