/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useState } from "react";
import { useGLTF, Decal, useTexture } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import BookScreen from '../assets/3d/book.glb'
import Cover from '../assets/psychology_of_money.png'
export function Book(props) {
  const [isPress, setIsPress] = useState(false)
  const { nodes, materials } = useGLTF(BookScreen);
  const refBook = useRef()
  const textureCover = useTexture('/psychology_of_money.jpg')
  console.log(textureCover, "texturcober", Cover)
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  // const dampingFactor = 0.95
  const { gl, viewport } = useThree()

  const handlePointerUp = (e) => {
    e.stopPropagation()
    e.preventDefault()
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const delta = (clientX - lastX.current) / viewport.width;
    refBook.current.rotation.z -= delta * 0.1 * Math.PI
    lastX.current = clientX
    rotationSpeed.current = delta * 0.01 * Math.PI;
    setIsPress(false)

  }

  const handlePointerDown = (e) => {
    e.stopPropagation()
    e.preventDefault()
    setIsPress(true)
  }

  const handlePointerMove = (e) => {
    e.stopPropagation()
    e.preventDefault()

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    if (isPress == true) {
      const delta = (clientX - lastX.current) / viewport.width;

      refBook.current.rotation.z -= delta * 0.1 * Math.PI
      lastX.current = clientX
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }
  const handlePointerLeave = (e) => {
    e.stopPropagation()
    e.preventDefault()
    setIsPress(false)
  }
  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointermove", handlePointerMove);
    canvas.addEventListener("pointerup", handlePointerUp)
    canvas.addEventListener("pointerdown", handlePointerDown)
    canvas.addEventListener("pointerleave", handlePointerLeave)
    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointermove", handlePointerMove);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointerdown", handlePointerDown)
      canvas.removeEventListener("pointerleave", handlePointerLeave)
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gl, handlePointerMove]);

  useFrame(() => {
    // refBook.current.rotation.z += rotationSpeed.current;
  })
  return (
    <group {...props} ref={refBook} dispose={null}>
      <group position={[0, 0.003, 0]} scale={[0.89, 0.116, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
        material={materials["Material.005"]}
        material-roughness={1}
        >
          <Decal
            position={[-4, -1, 1]}
            scale={[8, 1, 3]}
            rotation={[0, 0, 0]}

          >
            <meshBasicMaterial
              map={textureCover}
            />
          </Decal>

        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_3.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.006"]}
        position={[0.007, 0.003, 0]}
        scale={[0.89, 0.116, 1]}
      >

      </mesh>
    </group>
  );
}

useGLTF.preload("/book.glb");

